server:
  port: 10010
spring:
  application:
    name: spring-gateway
  cloud:
    gateway:
      routes:
        - id: employee-service-route
          uri: http://127.0.0.1:8080
          predicates:
            - Path=/consumer/**
  main:
    web-application-type: reactive

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka,http://127.0.0.1:10087/eureka