

jdbc:
  driver-class: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://localhost:3306/emmn?serverTimezone=Asia/Shanghai
  username: root
  password: lw880814

#mybatis:
#  configuration:
#    map-underscore-to-camel-case: true
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl



mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
server:
  port: ${port:9090}
spring:
  application:
    name: employee-service
#  config:
#    location: classpath:application.yml

eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka,http://localhost:10087/eureka
hystrix:
  metrics:
    polling-interval-ms: 3000