server:
  port: 8080

spring:
  application:
    name: service-consumer
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
feign:
  circuitbreaker:
    enabled: true
logging:
  level:
    com.szxxwang: debug


